[package]
name = "github-star-counter"
version = "0.1.0"
authors = ["Sebastian Thiel <sthiel@thoughtworks.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "count-github-stars"
path = "src/main/mod.rs"

[dependencies]
# lib
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"
itertools = "0.8.0"
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }
tokio = { git = "https://github.com/tokio-rs/tokio" }
base64 = "0.10.1"

# TODO Want request with await support, instead of hyper!
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls", version = "0.3.2" }

# main
structopt = "0.2.18"

[patch."https://github.com/hyperium/hyper"]
hyper = { git = "https://github.com/Byron/hyper" }

[dev-dependencies]
lazy_static = "1.3.0"
pretty_assertions = "0.6.1"
